site_name: FlightAware2columbus
site_description: FlightAware2columbus
site_author: Ken Lai
repo_url: https://github.com/KenMercusLai/FlightAware2columbus

theme: readthedocs

pages:
- Home: index.md
- About:
  - Release Notes: about/changelog.md
  - Contributing: about/contributing.md
  - License: about/license.md
