site_name: IJCAI18
site_description: IJCAI-18
site_author: Ken Lai
repo_url: https://github.com/KenMercusLai/testrepo

theme: readthedocs

pages:
- Home: index.md
- About:
  - Release Notes: about/changelog.md
  - Contributing: about/contributing.md
  - License: about/license.md
